name: souq_al_balad
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.3.2
  dio: ^5.4.0
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  material_design_icons_flutter: ^7.0.7296
  flutter_overboard: ^3.1.1
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.2
  easy_date_timeline: ^2.0.9
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  smooth_page_indicator: ^1.1.0
  country_flags: ^3.3.0
  fluttertoast: ^8.2.4
  country_code_picker: ^3.0.0
  flutter_typeahead: ^5.0.1
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.3
  image_picker: ^1.0.7
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  flutter_bloc: ^9.1.1
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^3.1.1
  pinput: ^5.0.1
  equatable: ^2.0.7
  loading_animation_widget: ^1.3.0
  geocode: ^1.0.3
  page_view_dot_indicator: ^2.3.0
  firebase_messaging: ^15.2.10
  firebase_core: ^3.15.2
  flutter_local_notifications: ^19.4.0
  shimmer_animation: ^2.2.2
  pusher_channels_flutter: ^2.5.0
  google_place: ^0.4.7
dependency_overrides:
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/l10n/
    - assets/l10n/ar.json
    - assets/l10n/en.json
    - assets/l10n/tr.json
    - assets/l10n/de.json

  # إضافة خطوط Montserrat المخصصة
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
